2024-01-13T21:47:09 {"cpu": 0.30859375, "cpu_total": 2, "cpu_usage": 0.154296875, "memory": 1523.0, "memory_total": 3908.0, "memory_usage": 0.3897134083930399, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "graceful_aspen", "hostname": "26dfcbb13f38", "level": "INFO", "message": "Pipeline graceful_aspen for run 1 in schedule 1 is alive.", "timestamp": 1705182429.64977, "uuid": "4862efbfc7ff42d88e5f633de659906a"}
2024-01-13T21:47:09 {"cpu": 0.30859375, "cpu_total": 2, "cpu_usage": 0.154296875, "memory": 1552.0, "memory_total": 3908.0, "memory_usage": 0.3971340839303992, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "graceful_aspen", "hostname": "26dfcbb13f38", "level": "INFO", "message": "Pipeline graceful_aspen for run 1 in schedule 1 is alive.", "timestamp": 1705182429.903825, "uuid": "27190e3fc7ae4b41bc904ceddb494324"}
2024-01-13T21:47:10 {"block_run_id": 1, "block_uuid": "open_data_toronto", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "graceful_aspen", "hostname": "26dfcbb13f38", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 1: pipeline graceful_aspen block open_data_toronto", "timestamp": 1705182430.008607, "uuid": "e2200ef3da324236803ba7384b70287e"}
2024-01-13T21:47:10 {"block_run_id": 1, "block_uuid": "open_data_toronto", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "graceful_aspen", "hostname": "26dfcbb13f38", "level": "INFO", "message": "BlockRun 1 (block_uuid: open_data_toronto) completes.", "timestamp": 1705182430.774337, "uuid": "7bbef9b3da0f4f4aa72966997d596923"}
2024-01-13T21:47:19 {"cpu": 0.32177734375, "cpu_total": 2, "cpu_usage": 0.160888671875, "memory": 1559.0, "memory_total": 3908.0, "memory_usage": 0.3989252814738997, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "graceful_aspen", "hostname": "26dfcbb13f38", "level": "INFO", "message": "Pipeline graceful_aspen for run 1 in schedule 1 is alive.", "timestamp": 1705182439.408075, "uuid": "f47ecb5e753649fe929980d03b85df17"}
2024-01-13T21:47:20 {"block_run_id": 2, "block_uuid": "green_aspen", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "graceful_aspen", "hostname": "26dfcbb13f38", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 2: pipeline graceful_aspen block green_aspen", "timestamp": 1705182440.10107, "uuid": "5c05c7edd62f4614af5da0ef4cbab0fd"}
2024-01-13T21:47:29 {"cpu": 0.345703125, "cpu_total": 2, "cpu_usage": 0.1728515625, "memory": 1688.0, "memory_total": 3908.0, "memory_usage": 0.43193449334698053, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "graceful_aspen", "hostname": "26dfcbb13f38", "level": "INFO", "message": "Pipeline graceful_aspen for run 1 in schedule 1 is alive.", "timestamp": 1705182449.964774, "uuid": "297ff81edbe9453db4fee3d46ee932ef"}
2024-01-13T21:47:37 {"block_run_id": 2, "block_uuid": "green_aspen", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "graceful_aspen", "hostname": "26dfcbb13f38", "level": "EXCEPTION", "message": "BlockRun 2 (block_uuid: green_aspen) failed.", "timestamp": 1705182457.342646, "uuid": "a4588060f1ef4bd7a53a334acad93e3d", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 625, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 598, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1085, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1295, in execute_sync\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1213, in execute_sync\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1519, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/r/__init__.py\", line 158, in _execute_block\n    outputs = execute_r_code(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/r/__init__.py\", line 57, in execute_r_code\n    __execute_r_code(file_path)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/r/__init__.py\", line 139, in __execute_r_code\n    subprocess.run(\n  File \"/usr/local/lib/python3.10/subprocess.py\", line 526, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command '['Rscript', '--vanilla', '/tmp/a6fd638f-423c-49a7-9f04-80a95d4930aa.r']' returned non-zero exit status 1.\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 163, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 649, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 75, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 38, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1552, in schedule_all\n    PipelineScheduler(r).start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 149, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 182, in start\n    self.schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 149, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 319, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 581, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 27, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 99, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 165, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 262, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 227, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1105, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 641, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 149, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 415, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 59, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["Command '['Rscript', '--vanilla', '/tmp/a6fd638f-423c-49a7-9f04-80a95d4930aa.r']' returned non-zero exit status 1."]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 625, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 598, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1085, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1295, in execute_sync
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1213, in execute_sync
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1519, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/r/__init__.py", line 158, in _execute_block
    outputs = execute_r_code(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/r/__init__.py", line 57, in execute_r_code
    __execute_r_code(file_path)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/r/__init__.py", line 139, in __execute_r_code
    subprocess.run(
  File "/usr/local/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['Rscript', '--vanilla', '/tmp/a6fd638f-423c-49a7-9f04-80a95d4930aa.r']' returned non-zero exit status 1.
2024-01-13T21:47:39 {"cpu": 0.375, "cpu_total": 2, "cpu_usage": 0.1875, "memory": 1801.0, "memory_total": 3908.0, "memory_usage": 0.46084953940634593, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "graceful_aspen", "hostname": "26dfcbb13f38", "level": "INFO", "message": "Pipeline graceful_aspen for run 1 in schedule 1 is alive.", "timestamp": 1705182459.54483, "uuid": "026d20ae39bf4d3fbe398f463705cc4f"}
